-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Asignacion_reunion"
(
    idasignacion integer NOT NULL,
    "idContactos" integer NOT NULL,
    "idReuniones" integer NOT NULL,
    CONSTRAINT idasignacion PRIMARY KEY (idasignacion)
);

CREATE TABLE IF NOT EXISTS public."Clientes"
(
    idcliente integer NOT NULL,
    "First_Name" character varying COLLATE pg_catalog."default",
    "Last_Name" character varying COLLATE pg_catalog."default",
    "Number_Phone" integer,
    "Address" character varying COLLATE pg_catalog."default",
    "idContactos" integer NOT NULL,
    CONSTRAINT "Clientes_pkey" PRIMARY KEY (idcliente)
);

CREATE TABLE IF NOT EXISTS public."Contactos"
(
    "idContacto" integer NOT NULL,
    name character varying COLLATE pg_catalog."default",
    rol character varying COLLATE pg_catalog."default",
    number_phone integer,
    CONSTRAINT "idContacto" PRIMARY KEY ("idContacto")
);

CREATE TABLE IF NOT EXISTS public."Proyectos"
(
    "idProyecto" integer NOT NULL,
    "Nombre" character varying COLLATE pg_catalog."default",
    "Description" character varying COLLATE pg_catalog."default",
    cost real,
    state boolean,
    "idClientes" integer NOT NULL,
    CONSTRAINT "Proyectos_pkey" PRIMARY KEY ("idProyecto")
);

CREATE TABLE IF NOT EXISTS public."Reuniones"
(
    "idReuniones" integer NOT NULL,
    "Description" character varying COLLATE pg_catalog."default",
    date date,
    idcliente integer NOT NULL,
    idproyectos integer NOT NULL,
    CONSTRAINT idproyectos PRIMARY KEY ("idReuniones")
);

ALTER TABLE IF EXISTS public."Asignacion_reunion"
    ADD CONSTRAINT "idContactos" FOREIGN KEY ("idContactos")
    REFERENCES public."Contactos" ("idContacto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asignacion_reunion"
    ADD CONSTRAINT idreuniones FOREIGN KEY ("idReuniones")
    REFERENCES public."Reuniones" ("idReuniones") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Clientes"
    ADD CONSTRAINT "idContactos" FOREIGN KEY ("idContactos")
    REFERENCES public."Contactos" ("idContacto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Proyectos"
    ADD CONSTRAINT "idClientes" FOREIGN KEY ("idClientes")
    REFERENCES public."Clientes" (idcliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Reuniones"
    ADD CONSTRAINT "idProyectos" FOREIGN KEY (idproyectos)
    REFERENCES public."Proyectos" ("idProyecto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Reuniones"
    ADD CONSTRAINT idcliente FOREIGN KEY (idcliente)
    REFERENCES public."Clientes" (idcliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;